(() => {
  const store=new StorageProvider(), state=new NovaState(), model=new ModelProvider(), demo=new DemoService(), files=new FileService(), speech=new SpeechProvider(), screen=new ScreenService();
  const $=id=>document.getElementById(id); const messages=$('messages'), prompt=$('prompt'), preview=$('previewFrame');
  const restore=store.load(); if (restore) { state.conversations=restore.conversations || []; state.currentId=restore.currentId || null; state.files=restore.files || []; } if (!state.currentId) state.newConversation();
  const save=()=>store.save({conversations:state.conversations,currentId:state.currentId,files:state.files});
  const escape=text=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function render() { const c=state.current(); $('conversationTitle').textContent=c.title; $('providerStatus').textContent='Source : démo locale · quota : non applicable'; messages.innerHTML=''; c.messages.forEach(m=>{const el=document.createElement('article');el.className=`message ${m.role}`;el.innerHTML=`<div>${escape(m.text)}</div><div class="meta">${m.role==='user'?'Toi':'Nova'} · ${new Date(m.at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</div>`;messages.append(el);}); messages.scrollTop=messages.scrollHeight;
    const list=$('conversationList');list.innerHTML='';state.conversations.forEach(item=>{const b=document.createElement('button');b.className='conversation-item'+(item.id===state.currentId?' active':'');b.textContent=item.title;b.onclick=()=>{state.currentId=item.id;render();save();};list.append(b);});
    const fl=$('fileList');fl.innerHTML=''; if(!state.files.length) fl.innerHTML='<p class="empty">Les fichiers générés apparaîtront ici.</p>'; state.files.forEach((file,i)=>{const b=document.createElement('button');b.className='file-item'+(i===0?' active':'');b.textContent=`${file.path} · ${file.language}`;b.onclick=()=>{files.preview(preview,file);};fl.append(b);}); $('fileCount').textContent=`${state.files.length} fichier${state.files.length>1?'s':''}`; const disabled=!state.files.length; $('runButton').disabled=disabled;$('stopButton').disabled=disabled;$('downloadButton').disabled=disabled;
  }
  async function submit() { const text=prompt.value.trim(); if(!text) return; const c=state.current(); c.messages.push({role:'user',text,at:new Date().toISOString()}); if(c.messages.length===1)c.title=text.slice(0,38); prompt.value='';render(); $('sendButton').disabled=true; try { const result=await demo.respond(text); c.messages.push({role:'assistant',text:result.text,at:new Date().toISOString()}); if(result.files?.length){state.files=result.files; files.preview(preview,state.files[0]);} } catch(e) { c.messages.push({role:'assistant',text:`Erreur : ${e.message}`,at:new Date().toISOString()}); } finally {$('sendButton').disabled=false;save();render();} }
  $('composer').onsubmit=e=>{e.preventDefault();submit();}; prompt.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}};
  $('newChatButton').onclick=()=>{state.newConversation();state.files=[];files.stop(preview);save();render();};
  $('runButton').onclick=()=>files.preview(preview,state.files[0]); $('stopButton').onclick=()=>files.stop(preview); $('downloadButton').onclick=()=>files.download(state.files[0]);
  $('exportButton').onclick=()=>{const blob=new Blob([store.export({conversations:state.conversations,currentId:state.currentId,files:state.files})],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`nova-export-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);};
  $('importInput').onchange=async e=>{try{const data=store.import(await e.target.files[0].text());state.conversations=data.conversations;state.currentId=data.currentId||data.conversations[0]?.id;state.files=data.files||[];if(!state.currentId)state.newConversation();save();render();}catch(err){alert(err.message);}e.target.value='';};
  $('voiceButton').onclick=async()=>{const b=$('voiceButton');if(speech.listening){speech.stop();return;} try{b.classList.add('active');await speech.listen(text=>prompt.value=text);}catch(err){alert('Micro : '+err.message);}finally{b.classList.remove('active');}};
  $('screenButton').onclick=async()=>{const b=$('screenButton');try{if(screen.active())screen.stop();else await screen.start();b.classList.toggle('active',screen.active());$('screenNotice').classList.toggle('hidden',!screen.active());}catch(err){alert('Partage d’écran : '+err.message);b.classList.remove('active');$('screenNotice').classList.add('hidden');}};
  render();
})();
