import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.178.0/build/three.module.js';
import { invoke } from 'https://cdn.jsdelivr.net/npm/@tauri-apps/api@2.8.0/core/+esm';
const API=localStorage.getItem('jarvis_api')||'https://jarvis-assistant-4wy2.onrender.com';
const messages=document.querySelector('#messages'), input=document.querySelector('#input'), state=document.querySelector('#state'), label=document.querySelector('#orbLabel');
let session=localStorage.getItem('jarvis_session')||crypto.randomUUID();localStorage.setItem('jarvis_session',session);
function add(role,text){const x=document.createElement('div');x.className='message '+role;x.textContent=text;messages.appendChild(x);messages.scrollTop=messages.scrollHeight;return x;}
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(45,1,.1,100), renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(devicePixelRatio);document.querySelector('#orb').appendChild(renderer.domElement);camera.position.z=3;
const geo=new THREE.IcosahedronGeometry(1,5), mat=new THREE.MeshStandardMaterial({color:0x55e7ff,emissive:0x073c55,emissiveIntensity:2,roughness:.25,metalness:.2,wireframe:false});const orb=new THREE.Mesh(geo,mat);scene.add(orb);scene.add(new THREE.PointLight(0x55e7ff,15,8));
function resize(){const b=document.querySelector('#orb').getBoundingClientRect();renderer.setSize(b.width,b.height);camera.aspect=b.width/b.height;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
let pulse=0;function animate(t){requestAnimationFrame(animate);orb.rotation.x=t*.00025;orb.rotation.y=t*.00035;const s=1+Math.sin(t*.002)*.035+pulse*.12;orb.scale.setScalar(s);pulse*=.92;renderer.render(scene,camera);}animate(0);
function setState(s){state.textContent=s;label.textContent=s==='Écoute'?'Je t’écoute':s==='Réflexion'?'Je réfléchis':s==='Parle'?'Je te réponds':'Prêt';mat.emissiveIntensity=s==='Réflexion'?4:s==='Parle'?3:2;pulse=.8;}
async function send(){const text=input.value.trim();if(!text)return;add('user',text);input.value='';setState('Réflexion');const wait=add('assistant','Je réfléchis…');try{const r=await fetch(API+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:session,message:text})});const d=await r.json();wait.remove();const a=add('assistant',d.reply||d.error||'Erreur');if(d.artifact?.type==='code'){const b=document.createElement('button');b.className='artifact';b.textContent='▶ Tester le projet';b.onclick=async()=>{try{await invoke('open_preview',{html:d.artifact.content})}catch{const w=open();w.document.write(d.artifact.content);w.document.close()}};a.appendChild(b);}setState('Parle');if(d.reply&&'speechSynthesis'in window){const u=new SpeechSynthesisUtterance(d.reply);u.lang='fr-FR';u.rate=.95;speechSynthesis.speak(u);}setTimeout(()=>setState('Prêt'),2500);}catch(e){wait.textContent='Impossible de joindre Jarvis.';setState('Erreur');}}
document.querySelector('#send').onclick=send;input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}});document.querySelector('#mic').onclick=()=>{if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window))return;const R=window.SpeechRecognition||window.webkitSpeechRecognition;const r=new R();r.lang='fr-FR';r.onstart=()=>setState('Écoute');r.onresult=e=>{input.value=e.results[0][0].transcript;send()};r.onend=()=>setState('Prêt');r.start()};document.querySelector('#updateBtn').onclick=()=>location.reload();add('assistant','Bonjour. Je suis Jarvis. Demande-moi de coder un jeu, préparer un exposé ou t’aider à réfléchir.');
