(() => {
  const store=new StorageProvider(), state=new NovaState(), model=new ModelProvider(), demo=new DemoService(), files=new FileService(), speech=new SpeechProvider(), screen=new ScreenService();
  const $=id=>document.getElementById(id); const messages=$('messages'), prompt=$('prompt'), preview=$('previewFrame');
  const restored=store.load(); if(restored){state.conversations=restored.conversations||[];state.currentId=restored.currentId||null;state.files=restored.files||[];} if(!state.currentId)state.newConversation();
  const savedMode=localStorage.getItem('nova-route-mode')||'auto'; model.setMode(savedMode); $('routeMode').value=savedMode;
  const save=()=>store.save({conversations:state.conversations,currentId:state.currentId,files:state.files});
  const escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const label=result=>result.provider==='ollama-local'?'🟣 Local — Ollama':result.provider==='demo'?'🟠 Démo locale':`🟢 Cloud — ${result.provider}`;
  async function updateAvailability(){const a=await model.getAvailability();$('routeDetail').textContent=`${a.cloud?'Cloud configuré':'Cloud non configuré'} · ${a.local?'Ollama local disponible':'Ollama local indisponible'}`;$('modeBadge').textContent=model.getMode()==='auto'?'Automatique':model.getMode()==='local'?'Local seulement':model.getMode()==='cloud'?'Cloud seulement':'Démo seulement';}
  function render(){const c=state.current();$('conversationTitle').textContent=c.title;$('providerStatus').textContent='Routage : '+$('modeBadge').textContent;messages.innerHTML='';c.messages.forEach(m=>{const e=document.createElement('article');e.className=`message ${m.role}`;e.innerHTML=`<div>${escape(m.text)}</div><div class="meta">${m.role==='user'?'Toi':(m.source||'Nova')} · ${new Date(m.at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</div>`;messages.append(e);});messages.scrollTop=messages.scrollHeight;const list=$('conversationList');list.innerHTML='';state.conversations.forEach(item=>{const b=document.createElement('button');b.className='conversation-item'+(item.id===state.currentId?' active':'');b.textContent=item.title;b.onclick=()=>{state.currentId=item.id;save();render();};list.append(b);});const fl=$('fileList');fl.innerHTML='';if(!state.files.length)fl.innerHTML='<p class="empty">Les fichiers générés apparaîtront ici.</p>';state.files.forEach((f,i)=>{const b=document.createElement('button');b.className='file-item'+(i===0?' active':'');b.textContent=`${f.path} · ${f.language}`;b.onclick=()=>files.preview(preview,f);fl.append(b);});$('fileCount').textContent=`${state.files.length} fichier${state.files.length>1?'s':''}`;for(const id of ['runButton','stopButton','downloadButton'])$(id).disabled=!state.files.length;}
  async function submit(){const text=prompt.value.trim();if(!text)return;const c=state.current();c.messages.push({role:'user',text,at:new Date().toISOString()});if(c.messages.length===1)c.title=text.slice(0,38);prompt.value='';render();$('sendButton').disabled=true;try{let result;if(model.getMode()==='demo'){result=await demo.respond(text);result.provider='demo';}else{result=await model.generateResponse(text);if(result.provider==='demo'){const generated=await demo.respond(text);result={...result,...generated};}}c.messages.push({role:'assistant',text:result.text,source:label(result),at:new Date().toISOString()});if(result.files?.length){state.files=result.files;files.preview(preview,state.files[0]);}}catch(error){c.messages.push({role:'assistant',text:`Erreur : ${error.message}`,source:'Nova',at:new Date().toISOString()});}finally{$('sendButton').disabled=false;save();render();updateAvailability();}}
  $('composer').onsubmit=e=>{e.preventDefault();submit();};prompt.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}};$('routeMode').onchange=e=>{model.setMode(e.target.value);updateAvailability();render();};$('newChatButton').onclick=()=>{state.newConversation();state.files=[];files.stop(preview);save();render();};$('runButton').onclick=()=>files.preview(preview,state.files[0]);$('stopButton').onclick=()=>files.stop(preview);$('downloadButton').onclick=()=>files.download(state.files[0]);$('exportButton').onclick=()=>{const blob=new Blob([store.export({conversations:state.conversations,currentId:state.currentId,files:state.files})],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`nova-export-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);};$('importInput').onchange=async e=>{try{const d=store.import(await e.target.files[0].text());state.conversations=d.conversations;state.currentId=d.currentId||d.conversations[0]?.id;state.files=d.files||[];if(!state.currentId)state.newConversation();save();render();}catch(err){alert(err.message);}e.target.value='';};$('voiceButton').onclick=async()=>{const b=$('voiceButton');if(speech.listening){speech.stop();return;}try{b.classList.add('active');await speech.listen(t=>prompt.value=t);}catch(e){alert('Micro : '+e.message);}finally{b.classList.remove('active');}};$('screenButton').onclick=async()=>{const b=$('screenButton');try{if(screen.active())screen.stop();else await screen.start();b.classList.toggle('active',screen.active());$('screenNotice').classList.toggle('hidden',!screen.active());}catch(e){alert('Partage d’écran : '+e.message);b.classList.remove('active');$('screenNotice').classList.add('hidden');}};render();updateAvailability();
})();
